baseURL = 'https://github.com/geo-di-lab/emerge-lessons/'
languageCode = 'en-us'
title = 'EMERGE Lessons'

defaultContentLanguage = 'en'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'EMERGE Lessons'
    weight = 1

  [languages.es]
    languageCode = 'es'
    languageName = 'Español'
    title = 'Lecciones de EMERGE'
    weight = 2

[params]
  themeVariant = ['auto', 'blue', 'relearn-light', 'learn', 'relearn-dark']
  collapsibleMenu = true
  hideAuthorDate = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'